### ISSUE TITLE
Long author lists break instead of line wrapping

### ISSUE THREAD

**Issue by peterjc** [sanger-pathogens/gff3toembl#46]
Further to #45 about how to format the authors, if the author list is too long, rather than wrapping it into multiple ``RA`` lines we get an error, e.g.

```
$ gff3_to_embl --authors 'Jagger M., Richards K., Watts C., Wood R., Jones B., Stewart I., Wyman B., Taylor M.' --title 'Some title' --publication 'Some journal' --genome_type 'circular' --classification 'PROK' --output_filename /tmp/single_feature.embl --translation_table 11 Organism 1234 'My project' 'My description' gff3toembl/tests/data/single_feature.gff
Traceback (most recent call last):
  File "/usr/local/bin/gff3_to_embl", line 4, in <module>
    __import__('pkg_resources').run_script('gff3toembl==1.0.1', 'gff3_to_embl')
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 745, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 1677, in run_script
    exec(script_code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/gff3toembl-1.0.1-py2.7.egg/EGG-INFO/scripts/gff3_to_embl", line 38, in <module>
    
  File "build/bdist.macosx-10.10-intel/egg/gff3toembl/EMBLWriter.py", line 96, in parse_and_run
  File "build/bdist.macosx-10.10-intel/egg/gff3toembl/EMBLWriter.py", line 45, in create_output_file
  File "build/bdist.macosx-10.10-intel/egg/gff3toembl/EMBLContig.py", line 25, in format
ValueError: Could not format contig, a line exceeded 80 characters in length
```

**Comment by andrewjpage** [comment]
Thanks for letting us know. We usually just put in who submitted the genome and later EMBL automatically attach the references.

**Comment by andrewjpage** [comment]
Fixed

**Comment by peterjc** [comment]
Thank you - I like how you went with the Rolling Stones theme for the unit tests :+1:
