### ISSUE TITLE
No module named 'gt' from bioconda install 

### ISSUE THREAD

**Issue by tobsecret** [sanger-pathogens/gff3toembl#77]
Installed via bioconda, got the following error:
```
Traceback (most recent call last):                                                                    
  File "/scratch/schrat01/gff3_toembl_env/bin/gff3_to_embl", line 4, in <module>                         
    __import__('pkg_resources').run_script('gff3toembl==1.1.4', 'gff3_to_embl')                                                                   
  File "/scratch/schrat01/gff3_toembl_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 66
6, in run_script                                                         
self.require(requires)[0].run_script(script_name, ns)                
  File "/scratch/schrat01/gff3_toembl_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1460, in run_script                                                        
    exec(script_code, namespace, namespace)                              
  File "/scratch/schrat01/gff3_toembl_env/lib/python3.7/site-packages/gff3toembl-1.1.4-py2.7.egg/EGG-INFO/scripts/gff3_to_embl", line 8, in <module>                              
  File "/scratch/schrat01/gff3_toembl_env/lib/python3.7/site-packages/gff3toembl-1.1.4-py2.7.egg/gff3toembl/EMBLWriter.py", line 3, in <module>                                   
ModuleNotFoundError: No module named 'gt'                                
```
I created the environment with `conda create -p gff3_toembl_env/ bioconda::gff3toembl`.
Conda installed python 3.7 in that environment - does that work with the py2.7.egg ?
```
(gff3_toembl_env)[schrat01]$ conda list                   
# packages in environment at /scratch/schrat01/gff3_toembl_env:                                          
#                                                                        
# Name                    Version                   Build  Channel       
_libgcc_mutex             0.1                        main                
ca-certificates           2019.5.15                     1                
certifi                   2019.6.16                py37_1                
genometools-genometools   1.5.10               h470a237_1    bioconda    
gettext                   0.19.8.1             hd7bead4_3                
gff3toembl                1.1.4                      py_1    bioconda    
libedit                   3.1.20181209         hc058e9b_0                
libffi                    3.2.1                hd88cf55_4                
libgcc-ng                 9.1.0                hdf63c60_0                
libstdcxx-ng              9.1.0                hdf63c60_0                
ncurses                   6.1                  he6710b0_1                
openssl                   1.1.1d               h7b6447c_1                
pip                       19.2.2                   py37_0                
python                    3.7.4                h265db76_1                
readline                  7.0                  h7b6447c_5                
setuptools                41.0.1                   py37_0                
six                       1.12.0                   py37_0                
sqlite                    3.29.0               h7b6447c_0                
tk                        8.6.8                hbc83047_0                
wheel                     0.33.4                   py37_0                
xz                        5.2.4                h14c3975_4                
zlib                      1.2.11               h7b6447c_3                
```

**Comment by Aciole-David** [comment]
The installation is the "genometools-genometools".
